Repository qwertyOko/CmdRepport, pull requests merged in 2024-04, with the labels that each got.

#1 create interface
  CmdRepport/App.config
  CmdRepport/CmdRepport.csproj
  CmdRepport/CmdRepport.sln
  CmdRepport/Form1.Designer.cs
  CmdRepport/Form1.cs
  CmdRepport/Form1.resx
  CmdRepport/Program.cs
  CmdRepport/Properties/AssemblyInfo.cs
  CmdRepport/Properties/Resources.Designer.cs
  CmdRepport/Properties/Resources.resx
  CmdRepport/Properties/Settings.Designer.cs
  CmdRepport/Properties/Settings.settings
Labels: good first issue

#2 add logic for count fuel
  CmdRepport/Form1.Designer.cs
  CmdRepport/Form1.cs
Labels: enhancement

#3 add recommendations:
  CmdRepport/CmdRepport.csproj
  CmdRepport/Program.cs
  CmdRepport/bugReport.txt
Labels: bug, documentation

#5 added font and picture
  CmdRepport/CmdRepport.csproj
  CmdRepport/Form1.Designer.cs
  CmdRepport/Form1.cs
  CmdRepport/Program.cs
  CmdRepport/bugReport.txt
Labels: enhancement

#9 Add icons
  .gitignore
  CmdRepport/Form1.Designer.cs
  CmdRepport/Form1.ja-JP.resx
  CmdRepport/Form1.ja.resx
  CmdRepport/Form1.resx
  CmdRepport/Form1.ru.resx
  CmdRepport/Properties/Resources/sunny_moon.jpeg
Labels: bug

#11 added panel for Car model/Car brand/Engine size
  CmdRepport/Form1.Designer.cs
  CmdRepport/Form1.cs
  CmdRepport/Form1.resx
Labels: enhancement
